### ISSUE TITLE
Define easy method to Get breakpoints coordinates, and segments parameters as tuples.

### ISSUE THREAD

**Issue by ABDsheikho** [chasmani/piecewise-regression#14]
Hi, I like this package and I want to share some Ideas to develop it:

```
# after that I do the fitt
pw_fit = piecewise_regression.Fit(xx, yy, n_breakpoints=3)
``` 
why there is no easy method to get list of tuples that represents breakpoints coordinates? or even list of tuples of segments parameters.

yeah I know I can extract this stuff by myself from the current summery. but wouldn't that be more helpful?!
something like:
```
breakpoints = pw_fit.breakpoints_list()
# the return would be like breakpoints = [ (x1,y1),  (x2,y2), (x3,y3) ]

# and for segments parameters:
line1, line2, line3 = pw_fit.lines_params()
# the return would be like   [ (slope1, intercept1), (slope2, intercept2), (slope3, intercept3) ]
```
and than maybe I can preform tuple unpacking
```
slope1, intercept1 = line1
slope2, intercept2 = line2
slope3, intercept3 = line3
```
thank you for your consideration.

**Comment by chasmani** [comment]
Thank you. I added a method get_params to the fitted model.
