### ISSUE TITLE
Please add min_breakpoints parameter for ModelSelection

### ISSUE THREAD

**Issue by peascod206** [chasmani/piecewise-regression#15]
IMHO, users should, in most cases, have some rough idea about the min breakponits in their data.  By allowing users to specify the min breakpoints in the ModelSelection function, it'll save the model fitting time for the model with 1 breakpoints upto (min_breakpoints - 1) breakpoints. 

Thanks

**Comment by chasmani** [comment]
Thank you for your suggestion. While this may help some users, it would also increase the complexity of the tool and add some technical burden, as well as the cost in terms of development time. At this point we do not anticipate that this benefit is worth the cost.
