### ISSUE TITLE
not having a function to get the y predictions

### ISSUE THREAD

**Issue by krishnasrujan** [chasmani/piecewise-regression#5]
Hello, 
It's good to have such a useful package for segmented regression, but I don't see any function to get the predictions directly. Can you just create another function that returns the predictions, the code is already present in plot_fit function inside Fit class.

**Comment by placid2000** [comment]
Thank you for the library!

Indeed a function to predict new data points would be very convenient.
Something like
`y_pred = pw_fit.predict(X)
`

**Comment by thegodone** [comment]
I vote for Placid2000 suggestion and it is not a nice to have feature, basically ploting does the same but we don't always plot results especially on large data.

**Comment by chasmani** [comment]
Implemented! fit.predict(x) not does this. Thanks for the suggestion!
