### ISSUE TITLE
Including uncertainties on measurements

### ISSUE THREAD

**Issue by grejka** [chasmani/piecewise-regression#7]
Hi:)
Thank you for this very helpful package and the explanatory accompanying paper. 
I am currently using it to fit data where I have uncertainties on both x- and y-values, so I wanted to ask if it would be possible to include them in the fitting process to make it more accurate?
Best regards,
Jana

**Comment by chasmani** [comment]
Hi Jana

There isn’t the functionality to do that currently. I’m not sure how you
would implement it, maybe need to use a Bayesian approach. Maybe there is
an r package that can do it.

Best
Charlie

**Comment by grejka** [comment]
Dear Charlie,
Thanks for your answer. I will try to find a way to implement this.
Cheers,
Jana
