### ISSUE TITLE
sklearn-compatibility of function name and instance

### ISSUE THREAD

**Issue by jckkvs** [chasmani/piecewise-regression#8]
Thank you for providing a useful library.

I think that compatibility with scikit-learn is high as one way to improve the usability of machine learning models.

In particular, I think the following two specifications have low compatibility.

Fit is designed as a class, not a function.
A specification that requires X and y when creating an instance in "class Muggeo".

It's just my opinion.

**Comment by chasmani** [comment]
Thank you. Yes compatibility with other libraries would be desirable. On reflection, changes of that nature would involve a lot of development work and we do not think that the benefit would be worth the cost at this time.
